from ..baseImporter import vars
from ..enums import aspectRatios
from .rect import Rect
from typing_extensions import overload

class ScreenUnit:
    @staticmethod
    def percent(parentSize: vars.validScreenUnit, percent: int | float) -> int | float: ...
    
    @staticmethod
    def dw(screenUnit: vars.validScreenUnit) -> vars.validScreenUnit: ...
    @staticmethod
    def dh(screenUnit: vars.validScreenUnit) -> vars.validScreenUnit: ...
    @staticmethod
    def vw(screenUnit: vars.validScreenUnit) -> vars.validScreenUnit: ...
    @staticmethod
    def vh(screenUnit: vars.validScreenUnit) -> vars.validScreenUnit: ...
    @staticmethod
    def px(screenUnit: int) -> int: ...
    
    @staticmethod
    def getVwFromPx(xPixel: int) -> vars.validScreenUnit: ...
    @staticmethod
    def getVhFromPx(yPixel: int) -> vars.validScreenUnit: ...
    
    @staticmethod
    def getRelativePostion(coordinate: vars.coordinate) -> tuple[vars.validScreenUnit]: ...
    
    @staticmethod
    def aspectRatioFromInt(xRatio: int, yRatio: int) -> vars.validScreenUnit: ...
    @staticmethod
    def aspectRatioFromString(aspectRatio: str | aspectRatios) -> vars.validScreenUnit: ...
    
    @staticmethod
    def checkIfValidScreenUnit(screenUnit) -> vars.validScreenUnit: ...
    @staticmethod
    def convertMultipleUnits(*screenUnit) -> list[vars.validScreenUnit]: ...
    
    @staticmethod
    def centerOfScreen() -> tuple[vars.validScreenUnit]: ...
    
    @overload
    @staticmethod
    def centerRectInScreen(rect: Rect) -> tuple[vars.validScreenUnit]: ...
    @overload
    @staticmethod
    def centerRectInScreen(width: vars.validScreenUnit, height: vars.validScreenUnit) -> tuple[vars.validScreenUnit]: ...
