from typing import overload
from widgets._baseWidget import _BaseWidget
from elements.colors import Color
import vars

class _ColoredWidget(_BaseWidget):
    @overload
    def __init__(self, size: tuple[vars.validScreenUnit, vars.validScreenUnit], color: vars.RGBvalue, borderRadius: int = -1) -> None: ...
    @overload
    def __init__(self, width: vars.validScreenUnit, height: vars.validScreenUnit, color: vars.RGBvalue, borderRadius: int = -1) -> None: ...
    
    def updateColor(self, newColor: vars.RGBvalue) -> None: ...
    
    def changeColorOnHover(self, hoverColor: vars.RGBvalue) -> None: ...
    def changeColorOnClick(self, clickColor: vars.RGBvalue) -> None: ...
    def changeColorOnPressing(self, clickColor: vars.RGBvalue) -> None: ...
    
    def disable(self, disableColor: vars.RGBvalue = Color.GRAY) -> None: ...
    def enable(self) -> None: ...
    